"""empty message

Revision ID: 48202878a6b2
Revises: 
Create Date: 2022-01-20 22:15:48.455443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48202878a6b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('file_name', sa.String(length=200), nullable=False))
    op.add_column('driver', sa.Column('original_file', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'original_file')
    op.drop_column('driver', 'file_name')
    # ### end Alembic commands ###
